import type { Metadata } from "next";
import { Orbitron } from '@next/font/google';
import { Roboto } from '@next/font/google';
import "./globals.css";

const orbitron = Orbitron({ 
  subsets: ['latin'], 
  variable: '--font-orbitron' 
});
const roboto = Roboto({
   subsets: ['latin'], 
   variable: '--font-roboto',
   weight:"400"
   });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
