/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ControllerProps = {};

type GLTFResult = GLTF & {
  nodes: {
    circlebutton: THREE.Mesh
    crossbutton: THREE.Mesh
    defaultMaterial: THREE.Mesh
    downarrowbutton: THREE.Mesh
    frontdesignpart: THREE.Mesh
    leftarrowbutton: THREE.Mesh
    leftfrontbutton: THREE.Mesh
    leftjoystick: THREE.Mesh
    leftjoystickcircle: THREE.Mesh
    lefttopbutton: THREE.Mesh
    rightarrowbutton: THREE.Mesh
    rightfrontbutton: THREE.Mesh
    rightjoystick: THREE.Mesh
    rightjoystickcircle: THREE.Mesh
    righttopbutton: THREE.Mesh
    squarebutton: THREE.Mesh
    topdesignpart: THREE.Mesh
    trianglebutton: THREE.Mesh
    uparrowbutton: THREE.Mesh
  }
  materials: { }
}

export function Console(props:ControllerProps ) {
  const { nodes, materials } = useGLTF('/controller.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Controller" position={[28.46, 21.11, -0.337]}>
              <mesh
                name="circlebutton"
                castShadow
                receiveShadow
                geometry={nodes.circlebutton.geometry}
                material={nodes.circlebutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="crossbutton"
                castShadow
                receiveShadow
                geometry={nodes.crossbutton.geometry}
                material={nodes.crossbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={nodes.defaultMaterial.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="downarrowbutton"
                castShadow
                receiveShadow
                geometry={nodes.downarrowbutton.geometry}
                material={nodes.downarrowbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="frontdesignpart"
                castShadow
                receiveShadow
                geometry={nodes.frontdesignpart.geometry}
                material={nodes.frontdesignpart.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="leftarrowbutton"
                castShadow
                receiveShadow
                geometry={nodes.leftarrowbutton.geometry}
                material={nodes.leftarrowbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="leftfrontbutton"
                castShadow
                receiveShadow
                geometry={nodes.leftfrontbutton.geometry}
                material={nodes.leftfrontbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="leftjoystick"
                castShadow
                receiveShadow
                geometry={nodes.leftjoystick.geometry}
                material={nodes.leftjoystick.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="leftjoystickcircle"
                castShadow
                receiveShadow
                geometry={nodes.leftjoystickcircle.geometry}
                material={nodes.leftjoystickcircle.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="lefttopbutton"
                castShadow
                receiveShadow
                geometry={nodes.lefttopbutton.geometry}
                material={nodes.lefttopbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="rightarrowbutton"
                castShadow
                receiveShadow
                geometry={nodes.rightarrowbutton.geometry}
                material={nodes.rightarrowbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="rightfrontbutton"
                castShadow
                receiveShadow
                geometry={nodes.rightfrontbutton.geometry}
                material={nodes.rightfrontbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="rightjoystick"
                castShadow
                receiveShadow
                geometry={nodes.rightjoystick.geometry}
                material={nodes.rightjoystick.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="rightjoystickcircle"
                castShadow
                receiveShadow
                geometry={nodes.rightjoystickcircle.geometry}
                material={nodes.rightjoystickcircle.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="righttopbutton"
                castShadow
                receiveShadow
                geometry={nodes.righttopbutton.geometry}
                material={nodes.righttopbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="squarebutton"
                castShadow
                receiveShadow
                geometry={nodes.squarebutton.geometry}
                material={nodes.squarebutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="topdesignpart"
                castShadow
                receiveShadow
                geometry={nodes.topdesignpart.geometry}
                material={nodes.topdesignpart.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="trianglebutton"
                castShadow
                receiveShadow
                geometry={nodes.trianglebutton.geometry}
                material={nodes.trianglebutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
              <mesh
                name="uparrowbutton"
                castShadow
                receiveShadow
                geometry={nodes.uparrowbutton.geometry}
                material={nodes.uparrowbutton.material}
                position={[-4.496, -0.684, 11.017]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/controller.gltf')
