/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mrSem (https://sketchfab.com/mrSem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-controller-3f0dafeca37e479399f2d90011c1e35a
Title: Game controller
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ConsoleProps = {

}

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh,
  };
  materials: {};
}

export function Console(props:ConsoleProps) {
  const { nodes } = useGLTF('/controller.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Controller" position={[28.46, 21.11, -0.337]}>
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={nodes.defaultMaterial.material}
              />
              
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/controller.gltf')
